# Generated by Django 5.2.9 on 2026-02-25 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Congress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Congreso"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Fin")),
                ("location", models.CharField(max_length=200, verbose_name="Sede")),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nombre completo"),
                ),
                (
                    "document_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Documento/ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "is_utp",
                    models.BooleanField(default=False, verbose_name="¿Es de la UTP?"),
                ),
                (
                    "utp_career",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ISC", "Ingeniería de Sistemas Computacionales"),
                            ("IC", "Ingeniería Civil"),
                            ("IE", "Ingeniería Electromecánica"),
                            ("II", "Ingeniería Industrial"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Carrera UTP",
                    ),
                ),
                (
                    "utp_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de curso"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREREGISTERED", "Pre-registrado"),
                            ("ACCREDITED", "Acreditado (Check-in)"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="PREREGISTERED",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="registro.congress",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="registro.participant",
                    ),
                ),
            ],
            options={
                "unique_together": {("participant", "congress")},
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "qr_image",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="registro.registration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BadgePrintLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("printed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Motivo (si es reimpresión)",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_logs",
                        to="registro.registration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Título de la charla"
                    ),
                ),
                ("speaker", models.CharField(max_length=150, verbose_name="Ponente")),
                ("room", models.CharField(max_length=100, verbose_name="Sala")),
                ("start_time", models.DateTimeField(verbose_name="Inicio")),
                ("end_time", models.DateTimeField(verbose_name="Fin")),
                ("capacity", models.PositiveIntegerField(verbose_name="Cupo máximo")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="registro.congress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "Aprobado"), ("REJECTED", "Rechazado")],
                        default="APPROVED",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Motivo de rechazo/duplicado",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="registro.participant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="registro.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("participant", "session")},
            },
        ),
    ]
