# Generated by Django 5.2.9 on 2026-03-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del Conferencista"
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        max_length=200, verbose_name="Institución o Empresa"
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        max_length=200, verbose_name="Tema o Especialidad"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="speakers/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="registro.congress",
                        verbose_name="Congreso",
                    ),
                ),
            ],
        ),
    ]
