# Generated by Django 5.2.9 on 2026-03-05 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0002_speaker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speaker",
            name="institution",
        ),
        migrations.AddField(
            model_name="speaker",
            name="country",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, verbose_name="País"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="speaker",
            name="specialty",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=200,
                verbose_name="Especialidad",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="speaker",
            name="topic",
            field=models.CharField(max_length=200, verbose_name="Tema a exponer"),
        ),
    ]
