# Generated by Django 5.2.9 on 2026-03-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0004_alter_speaker_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="country",
            field=models.CharField(
                choices=[
                    ("pa", "Panamá"),
                    ("co", "Colombia"),
                    ("cr", "Costa Rica"),
                    ("mx", "México"),
                    ("es", "España"),
                    ("ar", "Argentina"),
                    ("cl", "Chile"),
                    ("pe", "Perú"),
                    ("us", "Estados Unidos"),
                    ("br", "Brasil"),
                    ("de", "Alemania"),
                    ("uy", "Uruguay"),
                ],
                default="pa",
                max_length=2,
                verbose_name="País",
            ),
        ),
    ]
