# Generated by Django 5.2.9 on 2026-03-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0005_alter_speaker_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del Panelista"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=200, verbose_name="Especialidad"),
                ),
                (
                    "topic",
                    models.CharField(max_length=200, verbose_name="Tema del Foro"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("pa", "Panamá"),
                            ("co", "Colombia"),
                            ("cr", "Costa Rica"),
                            ("mx", "México"),
                            ("es", "España"),
                            ("ar", "Argentina"),
                            ("cl", "Chile"),
                            ("pe", "Perú"),
                            ("us", "Estados Unidos"),
                            ("br", "Brasil"),
                            ("de", "Alemania"),
                            ("uy", "Uruguay"),
                        ],
                        default="pa",
                        max_length=2,
                        verbose_name="País",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="forum_speakers/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_speakers",
                        to="registro.congress",
                        verbose_name="Congreso",
                    ),
                ),
            ],
        ),
    ]
