# Generated by Django 5.2.9 on 2026-03-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0006_forumspeaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título del Foro"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="forums/", verbose_name="Poster / Imagen promocional"
                    ),
                ),
                (
                    "moderator",
                    models.CharField(max_length=150, verbose_name="Moderador"),
                ),
                ("date_time", models.DateTimeField(verbose_name="Fecha y Hora")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Lugar/Sala"),
                ),
                (
                    "speakers_info",
                    models.TextField(
                        help_text="Escribe aquí los nombres, cargos y detalles de los expositores. Puedes usar saltos de línea.",
                        verbose_name="Información de Expositores",
                    ),
                ),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forums",
                        to="registro.congress",
                        verbose_name="Congreso",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ForumSpeaker",
        ),
    ]
