# Generated by Django 5.2.9 on 2026-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0007_forum_delete_forumspeaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="category",
            field=models.CharField(
                default="General",
                help_text="Ej: Foro sobre Semiconductores, Foro de Logística, etc.",
                max_length=150,
                verbose_name="Segmento / Tema del Foro",
            ),
        ),
    ]
