# Generated by Django 5.2.9 on 2026-03-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0008_forum_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="presentation_date",
            field=models.DateField(
                blank=True,
                help_text="Elige el día para agrupar al conferencista en la cartelera.",
                null=True,
                verbose_name="Fecha de Presentación",
            ),
        ),
    ]
